"""Derive loudness, onset strength and onset times from source/audio.wav into analysis.js.

Pure numpy on purpose: the scene only needs coarse reactivity (flicker, hits),
not musical beat tracking. Section times live in scene.js and were read off
Suno's own lyric video.
"""

import subprocess
from pathlib import Path

import numpy as np

HERE = Path(__file__).resolve().parent
SR, HOP, N = 22050, 441, 2048  # 20 ms frames


def main():
    pcm = subprocess.run(
        ["ffmpeg", "-v", "error", "-i", str(HERE / "source" / "audio.wav"),
         "-ac", "1", "-ar", str(SR), "-f", "f32le", "-"],
        capture_output=True, check=True,
    ).stdout
    x = np.frombuffer(pcm, np.float32)
    n = len(x) // HOP
    rms = np.sqrt((x[: n * HOP].reshape(n, HOP) ** 2).mean(1))

    pad, win = np.pad(x, (N // 2, N // 2)), np.hanning(N)
    spec = np.log1p(10 * np.abs(np.array([np.fft.rfft(pad[i * HOP:i * HOP + N] * win) for i in range(n)])))
    flux = np.r_[0, np.maximum(0, np.diff(spec, axis=0)).sum(1)]
    flux = np.maximum(flux - np.convolve(flux, np.ones(25) / 25, "same"), 0)

    r = np.clip(rms / np.percentile(rms, 99), 0, 1)
    f = np.clip(flux / np.percentile(flux, 99), 0, 1)
    onsets = []
    for i in range(1, n - 1):
        if f[i] > 0.45 and f[i] >= f[i - 1] and f[i] >= f[i + 1] and (not onsets or i - onsets[-1] > 4):
            onsets.append(i)

    q = lambda a: ",".join(str(int(round(v * 99))) for v in a)
    (HERE / "analysis.js").write_text(
        "// Generated by analyze.py from source/audio.wav: 50 Hz loudness and onset strength (0..99), onset times in s.\n"
        "const AUDIO_RATE = 50;\n"
        f"const AUDIO_RMS = [{q(r)}];\n"
        f"const AUDIO_FLUX = [{q(f)}];\n"
        f"const AUDIO_ONSETS = [{','.join(f'{i * HOP / SR:.2f}' for i in onsets)}];\n"
    )
    print(f"{n} frames, {len(onsets)} onsets")


if __name__ == "__main__":
    main()
