"""Derive loudness, onset strength and onset times of one song into <song>/analysis.js.

Pure numpy on purpose: scenes only need coarse reactivity (flicker, hits),
not musical beat tracking; tempo and lyric times are in the timing report
written by prepare.py.

    python tools/analyze.py neunundachtzig-tabs
"""

import subprocess
import sys
from pathlib import Path

import numpy as np

VIDEO = Path(__file__).resolve().parent.parent
SR, HOP, N = 22050, 441, 2048  # 20 ms frames


def load(path, sr=SR):
    pcm = subprocess.run(
        ["ffmpeg", "-v", "error", "-i", str(path), "-ac", "1", "-ar", str(sr), "-f", "f32le", "-"],
        capture_output=True, check=True,
    ).stdout
    return np.frombuffer(pcm, np.float32)


def rms_frames(x):
    n = len(x) // HOP
    return np.sqrt((x[: n * HOP].reshape(n, HOP) ** 2).mean(1))


def flux_frames(x):
    n = len(x) // HOP
    pad, win = np.pad(x, (N // 2, N // 2)), np.hanning(N)
    spec = np.log1p(10 * np.abs(np.array([np.fft.rfft(pad[i * HOP:i * HOP + N] * win) for i in range(n)])))
    flux = np.r_[0, np.maximum(0, np.diff(spec, axis=0)).sum(1)]
    return np.maximum(flux - np.convolve(flux, np.ones(25) / 25, "same"), 0)


def analyze(song_dir):
    src = song_dir / "source"
    x = load(src / "audio.wav")
    r = np.clip(rms_frames(x) / np.percentile(rms_frames(x), 99), 0, 1)
    flux = flux_frames(x)
    f = np.clip(flux / np.percentile(flux, 99), 0, 1)
    n = len(r)
    onsets = []
    for i in range(1, n - 1):
        if f[i] > 0.45 and f[i] >= f[i - 1] and f[i] >= f[i + 1] and (not onsets or i - onsets[-1] > 4):
            onsets.append(i)
    q = lambda a: ",".join(str(int(round(v * 99))) for v in a)
    lines = [
        "// Generated by tools/analyze.py from source/audio.wav: 50 Hz loudness and onset strength (0..99),",
        "// onset times in s, and the loudness of the separated vocals where available.",
        "const AUDIO_RATE = 50;",
        f"const AUDIO_RMS = [{q(r)}];",
        f"const AUDIO_FLUX = [{q(f)}];",
        f"const AUDIO_ONSETS = [{','.join(f'{i * HOP / SR:.2f}' for i in onsets)}];",
    ]
    if (src / "vocals.wav").exists():
        v = rms_frames(load(src / "vocals.wav"))[:n]
        lines.append(f"const AUDIO_VOX = [{q(np.clip(v / np.percentile(v, 99), 0, 1))}];")
    (song_dir / "analysis.js").write_text("\n".join(lines) + "\n")
    return n, len(onsets)


if __name__ == "__main__":
    n, k = analyze(VIDEO / sys.argv[1])
    print(f"{n} frames, {k} onsets")
